import { Customer, Transaction, TransactionStatus, TransactionType } from '@/types'

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'cus_001_alpha_remittance',
    type: 'business',
    email: 'ops@alpharemittance.com',
    status: 'approved',
    business_legal_name: 'Alpha Remittance Ltd',
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'cus_002_beta_payments',
    type: 'business',
    email: 'finance@betapay.io',
    status: 'approved',
    business_legal_name: 'Beta Payments Inc',
    created_at: '2024-02-20T09:00:00Z',
  },
  {
    id: 'cus_003_gamma_fx',
    type: 'business',
    email: 'admin@gammafx.co',
    status: 'pending',
    business_legal_name: 'Gamma FX Solutions',
    created_at: '2024-03-05T14:00:00Z',
  },
  {
    id: 'cus_004_delta_transfers',
    type: 'business',
    email: 'hello@deltatransfers.com',
    status: 'approved',
    business_legal_name: 'Delta Transfers Corp',
    created_at: '2024-03-18T11:00:00Z',
  },
]

function daysAgo(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

export const MOCK_TRANSACTIONS: Transaction[] = [
  // Alpha Remittance transactions
  {
    id: 'tx_a001f3b2c4d5e6a7b8c9',
    status: TransactionStatus.completed,
    type: TransactionType.off_ramp,
    sender: { amount: 5200, currency: 'USD', payment_rail: 'SWIFT', name: 'Alpha Remittance Ltd' },
    receiver: { amount: 4980, currency: 'EUR', payment_rail: 'SEPA' },
    receipt: { unblockpay_fee: 52 },
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
    finished_at: daysAgo(1),
    customer_id: 'cus_001_alpha_remittance',
  },
  {
    id: 'tx_a002g4c3d6f7a8b9e0c1',
    status: TransactionStatus.completed,
    type: TransactionType.on_ramp,
    sender: { amount: 3800, currency: 'EUR', payment_rail: 'SEPA', name: 'Müller GmbH' },
    receiver: { amount: 3970, currency: 'USD', payment_rail: 'ACH' },
    receipt: { unblockpay_fee: 38 },
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
    finished_at: daysAgo(2),
    customer_id: 'cus_001_alpha_remittance',
  },
  {
    id: 'tx_a003h5d4e7g8b9c0f1d2',
    status: TransactionStatus.processing,
    type: TransactionType.off_ramp,
    sender: { amount: 7100, currency: 'USD', payment_rail: 'WIRE', name: 'Alpha Remittance Ltd' },
    receiver: { amount: 6800, currency: 'GBP', payment_rail: 'FASTER_PAYMENTS' },
    receipt: { unblockpay_fee: 71 },
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
    customer_id: 'cus_001_alpha_remittance',
  },
  {
    id: 'tx_a004i6e5f8h9c0d1g2e3',
    status: TransactionStatus.completed,
    type: TransactionType.off_ramp,
    sender: { amount: 4600, currency: 'USD', payment_rail: 'SWIFT', name: 'Alpha Remittance Ltd' },
    receiver: { amount: 4400, currency: 'BRL', payment_rail: 'PIX' },
    receipt: { unblockpay_fee: 46 },
    created_at: daysAgo(4),
    updated_at: daysAgo(4),
    finished_at: daysAgo(4),
    customer_id: 'cus_001_alpha_remittance',
  },
  {
    id: 'tx_a005j7f6g9i0d1e2h3f4',
    status: TransactionStatus.failed,
    type: TransactionType.on_ramp,
    sender: { amount: 2900, currency: 'GBP', payment_rail: 'FASTER_PAYMENTS', name: 'Johnson & Co' },
    receiver: { amount: 3620, currency: 'USD', payment_rail: 'ACH' },
    receipt: { unblockpay_fee: 0 },
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
    finished_at: daysAgo(5),
    customer_id: 'cus_001_alpha_remittance',
  },
  {
    id: 'tx_a006k8g7h0j1e2f3i4g5',
    status: TransactionStatus.completed,
    type: TransactionType.off_ramp,
    sender: { amount: 6300, currency: 'USD', payment_rail: 'WIRE', name: 'Alpha Remittance Ltd' },
    receiver: { amount: 5950, currency: 'EUR', payment_rail: 'SEPA' },
    receipt: { unblockpay_fee: 63 },
    created_at: daysAgo(7),
    updated_at: daysAgo(7),
    finished_at: daysAgo(7),
    customer_id: 'cus_001_alpha_remittance',
  },
  // Beta Payments transactions
  {
    id: 'tx_b001l9h8i1k2f3g4j5h6',
    status: TransactionStatus.completed,
    type: TransactionType.off_ramp,
    sender: { amount: 8500, currency: 'USD', payment_rail: 'SWIFT', name: 'Beta Payments Inc' },
    receiver: { amount: 8100, currency: 'EUR', payment_rail: 'SEPA' },
    receipt: { unblockpay_fee: 85 },
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
    finished_at: daysAgo(1),
    customer_id: 'cus_002_beta_payments',
  },
  {
    id: 'tx_b002m0i9j2l3g4h5k6i7',
    status: TransactionStatus.awaiting_deposit,
    type: TransactionType.off_ramp,
    sender: { amount: 4200, currency: 'USD', payment_rail: 'ACH', name: 'Beta Payments Inc' },
    receiver: { amount: 3900, currency: 'MXN', payment_rail: 'SPEI' },
    receipt: { unblockpay_fee: 42 },
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
    customer_id: 'cus_002_beta_payments',
  },
  {
    id: 'tx_b003n1j0k3m4h5i6l7j8',
    status: TransactionStatus.completed,
    type: TransactionType.on_ramp,
    sender: { amount: 5500, currency: 'EUR', payment_rail: 'SEPA', name: 'Rodrigues Lda' },
    receiver: { amount: 5800, currency: 'USD', payment_rail: 'ACH' },
    receipt: { unblockpay_fee: 55 },
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
    finished_at: daysAgo(3),
    customer_id: 'cus_002_beta_payments',
  },
  {
    id: 'tx_b004o2k1l4n5i6j7m8k9',
    status: TransactionStatus.completed,
    type: TransactionType.off_ramp,
    sender: { amount: 9200, currency: 'USD', payment_rail: 'SWIFT', name: 'Beta Payments Inc' },
    receiver: { amount: 8750, currency: 'GBP', payment_rail: 'CHAPS' },
    receipt: { unblockpay_fee: 92 },
    created_at: daysAgo(6),
    updated_at: daysAgo(6),
    finished_at: daysAgo(6),
    customer_id: 'cus_002_beta_payments',
  },
  {
    id: 'tx_b005p3l2m5o6j7k8n9l0',
    status: TransactionStatus.cancelled,
    type: TransactionType.on_ramp,
    sender: { amount: 1800, currency: 'BRL', payment_rail: 'PIX', name: 'Santos ME' },
    receiver: { amount: 350, currency: 'USD', payment_rail: 'ACH' },
    receipt: { unblockpay_fee: 0 },
    created_at: daysAgo(8),
    updated_at: daysAgo(8),
    finished_at: daysAgo(8),
    customer_id: 'cus_002_beta_payments',
  },
  {
    id: 'tx_b006q4m3n6p7k8l9o0m1',
    status: TransactionStatus.completed,
    type: TransactionType.off_ramp,
    sender: { amount: 6800, currency: 'USD', payment_rail: 'WIRE', name: 'Beta Payments Inc' },
    receiver: { amount: 6500, currency: 'EUR', payment_rail: 'SEPA' },
    receipt: { unblockpay_fee: 68 },
    created_at: daysAgo(9),
    updated_at: daysAgo(9),
    finished_at: daysAgo(9),
    customer_id: 'cus_002_beta_payments',
  },
  {
    id: 'tx_b007r5n4o7q8l9m0p1n2',
    status: TransactionStatus.completed,
    type: TransactionType.off_ramp,
    sender: { amount: 3400, currency: 'USD', payment_rail: 'ACH', name: 'Beta Payments Inc' },
    receiver: { amount: 3200, currency: 'EUR', payment_rail: 'SEPA' },
    receipt: { unblockpay_fee: 34 },
    created_at: daysAgo(11),
    updated_at: daysAgo(11),
    finished_at: daysAgo(11),
    customer_id: 'cus_002_beta_payments',
  },
  // Gamma FX transactions
  {
    id: 'tx_c001s6o5p8r9m0n1q2o3',
    status: TransactionStatus.processing,
    type: TransactionType.off_ramp,
    sender: { amount: 2700, currency: 'USD', payment_rail: 'SWIFT', name: 'Gamma FX Solutions' },
    receiver: { amount: 2580, currency: 'EUR', payment_rail: 'SEPA' },
    receipt: { unblockpay_fee: 27 },
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
    customer_id: 'cus_003_gamma_fx',
  },
  {
    id: 'tx_c002t7p6q9s0n1o2r3p4',
    status: TransactionStatus.completed,
    type: TransactionType.on_ramp,
    sender: { amount: 4100, currency: 'EUR', payment_rail: 'SEPA', name: 'Kowalski Sp. z o.o.' },
    receiver: { amount: 4320, currency: 'USD', payment_rail: 'WIRE' },
    receipt: { unblockpay_fee: 41 },
    created_at: daysAgo(4),
    updated_at: daysAgo(4),
    finished_at: daysAgo(4),
    customer_id: 'cus_003_gamma_fx',
  },
  {
    id: 'tx_c003u8q7r0t1o2p3s4q5',
    status: TransactionStatus.error,
    type: TransactionType.off_ramp,
    sender: { amount: 3300, currency: 'USD', payment_rail: 'ACH', name: 'Gamma FX Solutions' },
    receiver: { amount: 3100, currency: 'GBP', payment_rail: 'FASTER_PAYMENTS' },
    receipt: { unblockpay_fee: 0 },
    created_at: daysAgo(7),
    updated_at: daysAgo(7),
    finished_at: daysAgo(7),
    customer_id: 'cus_003_gamma_fx',
  },
  // Delta Transfers transactions
  {
    id: 'tx_d001v9r8s1u2p3q4t5r6',
    status: TransactionStatus.completed,
    type: TransactionType.off_ramp,
    sender: { amount: 11500, currency: 'USD', payment_rail: 'SWIFT', name: 'Delta Transfers Corp' },
    receiver: { amount: 10900, currency: 'EUR', payment_rail: 'SEPA' },
    receipt: { unblockpay_fee: 115 },
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
    finished_at: daysAgo(2),
    customer_id: 'cus_004_delta_transfers',
  },
  {
    id: 'tx_d002w0s9t2v3q4r5u6s7',
    status: TransactionStatus.completed,
    type: TransactionType.off_ramp,
    sender: { amount: 7800, currency: 'USD', payment_rail: 'WIRE', name: 'Delta Transfers Corp' },
    receiver: { amount: 7400, currency: 'EUR', payment_rail: 'SEPA' },
    receipt: { unblockpay_fee: 78 },
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
    finished_at: daysAgo(3),
    customer_id: 'cus_004_delta_transfers',
  },
  {
    id: 'tx_d003x1t0u3w4r5s6v7t8',
    status: TransactionStatus.completed,
    type: TransactionType.on_ramp,
    sender: { amount: 6200, currency: 'EUR', payment_rail: 'SEPA', name: 'Fernandez SL' },
    receiver: { amount: 6500, currency: 'USD', payment_rail: 'ACH' },
    receipt: { unblockpay_fee: 62 },
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
    finished_at: daysAgo(5),
    customer_id: 'cus_004_delta_transfers',
  },
  {
    id: 'tx_d004y2u1v4x5s6t7w8u9',
    status: TransactionStatus.awaiting_deposit,
    type: TransactionType.off_ramp,
    sender: { amount: 5600, currency: 'USD', payment_rail: 'SWIFT', name: 'Delta Transfers Corp' },
    receiver: { amount: 5300, currency: 'GBP', payment_rail: 'CHAPS' },
    receipt: { unblockpay_fee: 56 },
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
    customer_id: 'cus_004_delta_transfers',
  },
  {
    id: 'tx_d005z3v2w5y6t7u8x9v0',
    status: TransactionStatus.completed,
    type: TransactionType.off_ramp,
    sender: { amount: 4900, currency: 'USD', payment_rail: 'ACH', name: 'Delta Transfers Corp' },
    receiver: { amount: 4650, currency: 'EUR', payment_rail: 'SEPA' },
    receipt: { unblockpay_fee: 49 },
    created_at: daysAgo(8),
    updated_at: daysAgo(8),
    finished_at: daysAgo(8),
    customer_id: 'cus_004_delta_transfers',
  },
  {
    id: 'tx_d006a4w3x6z7u8v9y0w1',
    status: TransactionStatus.completed,
    type: TransactionType.off_ramp,
    sender: { amount: 8900, currency: 'USD', payment_rail: 'WIRE', name: 'Delta Transfers Corp' },
    receiver: { amount: 8400, currency: 'EUR', payment_rail: 'SEPA' },
    receipt: { unblockpay_fee: 89 },
    created_at: daysAgo(10),
    updated_at: daysAgo(10),
    finished_at: daysAgo(10),
    customer_id: 'cus_004_delta_transfers',
  },
  {
    id: 'tx_d007b5x4y7a8v9w0z1x2',
    status: TransactionStatus.refunded,
    type: TransactionType.on_ramp,
    sender: { amount: 2100, currency: 'GBP', payment_rail: 'FASTER_PAYMENTS', name: 'Williams Ltd' },
    receiver: { amount: 2620, currency: 'USD', payment_rail: 'WIRE' },
    receipt: { unblockpay_fee: 0 },
    created_at: daysAgo(12),
    updated_at: daysAgo(12),
    finished_at: daysAgo(12),
    customer_id: 'cus_004_delta_transfers',
  },
]
